services:
  app:
    image: registry.henriquesf.me/avena-be:${IMAGE_TAG:-latest}
    container_name: avena-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
    depends_on:
      - postgres
    expose:
      - "3000"
    networks:
      - avena-network
      - npm

  postgres:
    image: postgres:17
    container_name: avena-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-avena}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-avena_db}
    volumes:
      - avena_db_data:/var/lib/postgresql/data
    networks:
      - avena-network

volumes:
  avena_db_data:
    driver: local

networks:
  avena-network:
    driver: bridge
  npm:
    external: true
