services:
  postgres:
    image: postgres:17
    container_name: avena-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: avena
      POSTGRES_PASSWORD: avena
      POSTGRES_DB: avena_db
    volumes:
        - avena_db_data:/var/lib/postgresql/data
volumes:
  avena_db_data:
    driver: local


